# Generated by Django 3.0.6 on 2020-06-09 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_course_abc_to_mti'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Courseold',
        ),
    ]
